TARGET	= libmatmult.so

LIBSRCS	= matmult_nat.c matmult_blk.c
LIBOBJS	= $(LIBSRCS:.c=.o)


OPT	= -g -O3
PIC	= -fPIC

CC	= gcc
CFLAGS= $(OPT) $(PIC) $(XOPTS) -std=c99

SOFLAGS = -shared
XLIBS	= -L /usr/lib64/atlas -lsatlas

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS)
