TARGET	= libmatmult.so
LIBSRCS	=
LIBOBJS	=

OPT	= -g -fast -xrestrict -xunroll=n unrolls loops -xprefetch -fns=yes -fsimple=2
PIC	= -fPIC

CC	= suncc
CFLAGS= $(OPT) $(PIC) $(XOPTS)

SOFLAGS = -shared
XLIBS	=

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS)
